CREATE DATABASE IF NOT EXISTS DOCSIM_DB;
USE DOCSIM_DB;

CREATE TABLE IF NOT EXISTS scan_results (
  id INT AUTO_INCREMENT PRIMARY KEY,
  file_name_1 VARCHAR(255) NOT NULL,
  file_name_2 VARCHAR(255) NOT NULL,
  similarity DECIMAL(6,2) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
